name: Android CI

permissions:
  contents: write
  pull-requests: read

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'android_keystore.jks'
          fileDir: '/home/runner/work/RecurringExpenseTracker/RecurringExpenseTracker/app/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Build APK
        run: ./gradlew :app:assembleRelease -x test
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Verify Signature
        run: $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner verify --print-certs app/build/outputs/apk/release/RecurringExpenseTracker_${{ github.event.inputs.version }}.apk
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: RecurringExpenseTracker
          path: app/build/outputs/apk/release/RecurringExpenseTracker_${{ github.event.inputs.version }}.apk
  release:
    name: Release APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: RecurringExpenseTracker
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## 🚀 New Features",
                  "labels": [
                    "feature"
                  ]
                },
                {
                  "title": "## 🐛 Bugs fixed",
                  "labels": [
                    "bug"
                  ]
                },
                {
                  "title": "## 🧪 Updated Translations",
                  "labels": [
                    "translations"
                  ]
                },
                {
                  "title": "## 💬 Minor Changes",
                  "labels": [
                    "cleanup / restructuring",
                    "dependencies"
                  ]
                }
              ],
              "pr_template": "- #{{TITLE}} by @#{{AUTHOR}} in ##{{NUMBER}}"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: mikepenz/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          draft: true
          files: RecurringExpenseTracker/RecurringExpenseTracker_${{ steps.get_version.outputs.version-without-v }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
